const AUTOCAPITALIZE_PROPERTY = "autocapitalize";
const AUTOCAPITALIZE_OFF = "off";
const AUTOCAPITALIZE_NONE = "none";
const AUTOCORRECT_PROPERTY = "autocorrect";
const AUTOCORRECT_OFF = "off";
const ELEMENT_INPUT_TYPE = "input";
const EMAIL_MONIKER = "EMAIL";
const ID_PROPERTY = "Id";
const NAME_PROPERTY = "name";
const SPELLCHECK_PROPERTY = "spellcheck";
const TYPE_PROPERTY = "type";
const USERNAME_MONIKER = "USERNAME";

module.exports = {
  AUTOCAPITALIZE_PROPERTY,
  AUTOCAPITALIZE_NONE,
  AUTOCAPITALIZE_OFF,
  AUTOCORRECT_PROPERTY,
  AUTOCORRECT_OFF,
  ELEMENT_INPUT_TYPE,
  EMAIL_MONIKER,
  ID_PROPERTY,
  NAME_PROPERTY,
  SPELLCHECK_PROPERTY,
  TYPE_PROPERTY,
  USERNAME_MONIKER
};
